#!/usr/bin/env bash
set -e
[ -n "$PYENV_DEBUG" ] && set -x

program="${0##*/}"
if [[ "$program" = "python"* ]]; then
  for arg; do
    case "$arg" in
    -c* | -- ) break ;;
    */* )
      if [ -f "$arg" ]; then
        export PYENV_FILE_ARG="$arg"
        break
      fi
      ;;
    esac
  done
fi

export PYENV_ROOT="/Users/nsomeya/Library/ApplicationSupport/iTerm2/iterm2env-53"
exec "/Users/nsomeya/Library/ApplicationSupport/iTerm2/iterm2env-53/pyenv/libexec/pyenv" exec "$program" "$@"
